site_name: Szymon Kaczmarek Homelab Documentation
theme:
  name: material
  font:
    text: JetBrainsMono
  features:
    - content.code.copy
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details